---

# System setup playbook


- name: Install CLI tools
  hosts: localhost
  connection: local
  vars:
    common_packages: [stow, git, neovim, tmux, fzf, ripgrep, fd-find, bat, podman]
    debian_specific: [vim]
    fedora_specific: [vim-enhanced]

  tasks:
    - name: Install required packages on Debian/Ubuntu
      apt:
        name: "{{ common_packages + debian_specific }}"
        state: present
        update_cache: true
      become: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install required packages on Fedora
      dnf:
        name: "{{ common_packages + fedora_specific }}"
        state: present
        update_cache: true
      become: true
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Source .bash_custom in .bashrc
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK: CUSTOM CONFIG"
        block: |

          # Load custom bash stuff
          if [ -f ~/.bash_custom ]; then
              . ~/.bash_custom
          fi
        state: present
        insertafter: EOF
        create: yes
